In [1]:
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import SMOTE 
from imblearn.under_sampling import RandomUnderSampler
from sklearn import svm
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import learning_curve
from sklearn.utils import shuffle
import scipy.stats as stats
from sklearn import preprocessing
import matplotlib.pyplot as plt
from imblearn.under_sampling import NearMiss
import pandas
from sklearn import model_selection
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import roc_curve, roc_auc_score
from matplotlib import pyplot as plt
import datetime as dt
import pickle
import time
import plotly.express as px
from sklearn.preprocessing import OneHotEncoder
from copy import deepcopy as dp
from xgboost import XGBClassifier
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.datasets import make_moons
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier,AdaBoostClassifier,GradientBoostingClassifier, VotingClassifier
from imblearn.ensemble import BalancedRandomForestClassifier
from imblearn.ensemble import BalancedBaggingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn import preprocessing
import plotly.express as px
import pandas as pd
import numpy as np
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.manifold import TSNE
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt

path = '/content/drive/MyDrive/SEMESTER_5_DATA/Machine Learning/ML_PROJECT/'

In [2]:
data_Test = pd.read_csv(path+"UNSW_NB15_testing-set.csv")
data_Train = pd.read_csv(path+"UNSW_NB15_training-set.csv")
data_Train.drop_duplicates()
selected = ["dur" , "sbytes", "dbytes", "sttl", "dttl", "sloss", "dloss",  "sload", "dload", "spkts", "dpkts", "swin", "dwin", "smean", "dmean", "trans_depth", "response_body_len", "sjit", "djit", "sinpkt" , "dinpkt", "tcprtt", "synack", "ackdat", "ct_state_ttl", "ct_flw_http_mthd", "ct_ftp_cmd", "ct_srv_src", "ct_srv_dst", "ct_dst_ltm","ct_src_ltm", "ct_src_dport_ltm", "ct_dst_sport_ltm", "ct_dst_src_ltm"]

In [ ]:
X = MinMaxScaler().fit_transform(data_Train[selected])
pca = PCA(n_components = 3, svd_solver='full')
pc = pca.fit_transform(X)

finalDf = pd.DataFrame(data = pc , columns = ['principal component 1', 'principal component 2' , 'principal component 3'])
fig = px.scatter_3d(finalDf, x='principal component 1', y='principal component 2', z='principal component 3',
              color=data_Train['attack_cat'])
fig.show()

Output hidden; open in https://colab.research.google.com to view.

In [ ]:
data = data_Train[selected]
scaler = MinMaxScaler()
scaler.fit(data)
X = scaler.fit_transform(data)
y = data_Train['attack_cat']
sss = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=0)
X_train, X_test, y_train, y_test = [],[],[],[]
for train_index, test_index in sss.split(X, y):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]   

X = PCA(n_components = 4, svd_solver='full').fit_transform(X_test)
print(X.shape)
tsne = TSNE(n_components=2).fit_transform(X)

finalDf = pd.DataFrame(data = tsne , columns = ['component 1', 'component 2'])
fig = px.scatter(finalDf, x='component 1', y='component 2', color=y_test, title="tSNE Plot")
fig.show()

In [3]:
dic = {'Normal':0, 'Backdoor':1, 'Analysis':2, 'Fuzzers':3, 'Shellcode':4, 'Reconnaissance':5, 'Exploits':6, 'DoS':7, 'Worms':8, 'Generic':9}
data_Train['attack_cat'] = data_Train['attack_cat'].map(dic)
data_Test['attack_cat'] = data_Test['attack_cat'].map(dic)

In [ ]:
print(np.unique(data_Train['attack_cat'],return_counts=True))

#data_Train1 = data_Train[(data_Train['label'] == 1) & ((data_Train['attack_cat'] == 3) | (data_Train['attack_cat'] == 5) | (data_Train['attack_cat'] == 6) | (data_Train['attack_cat'] == 7) | (data_Train['attack_cat'] == 9))]
#data_Test1  = data_Test[(data_Test['label'] == 1) & ((data_Test['attack_cat'] == 3) | (data_Test['attack_cat'] == 5) | (data_Test['attack_cat'] == 6) | (data_Test['attack_cat'] == 7) | (data_Test['attack_cat'] == 9))]

data_Train1 = data_Train[(data_Train['label'] == 1)]
data_Test1  = data_Test[(data_Test['label'] == 1)]

X_train = data_Train1[selected]
y_train = data_Train1['attack_cat']
X_test = data_Test1[selected]
y_test = data_Test1['attack_cat']

(array([0, 1, 3, 5, 6, 7, 9]), array([56000,  5009, 18184, 10491, 33393, 12264, 40000]))
             dur  sbytes  ...  ct_dst_sport_ltm  ct_dst_src_ltm
47911   0.000009     200  ...                 1               4
47912   0.000009     200  ...                 2               7
47913   0.000009     200  ...                 1               6
47914   0.000003     200  ...                 2               7
47915   0.000008     200  ...                 1               4
...          ...     ...  ...               ...             ...
175336  0.000009     114  ...                13              24
175337  0.505762     620  ...                 1               2
175338  0.000009     114  ...                 3              13
175339  0.000009     114  ...                14              30
175340  0.000009     114  ...                16              30

[119341 rows x 34 columns]
            id       dur proto  ... is_sm_ips_ports attack_cat  label
0            1  0.121478   tcp  ...          

In [4]:
X_train = data_Train[selected]
y_train = data_Train['attack_cat']
X_test = data_Test[selected]
y_test = data_Test['attack_cat']

In [ ]:
#@title
def prepare_inputs(X_train, X_test):
	ohe = OneHotEncoder()
	ohe.fit(X_train)
	X_train_enc = ohe.transform(X_train)
	X_test_enc = ohe.transform(X_test)
	return X_train_enc, X_test_enc
data_Train , data_Test = prepare_inputs(data_Train , data_Test)

In [ ]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.neural_network import MLPClassifier

from imblearn.ensemble import BalancedBaggingClassifier

from imblearn.ensemble import RUSBoostClassifier


for i in ['logistic','relu','tanh','identity']:

    clf = BalancedBaggingClassifier(base_estimator= make_pipeline(StandardScaler(),MLPClassifier(hidden_layer_sizes= (200, 100, 40), 
                                                                    solver = "sgd",
                                                                    alpha = 0.1,
                                                                    batch_size=1000,
                                                                    activation=i , 
                                                                    learning_rate = 'adaptive',
                                                                    #learning_rate_init=0.01,  
                                                                    random_state=1, 
                                                                    #verbose = True,
                                                                    max_iter=100
                                                                )), 
                    n_estimators=100, random_state=0)



                    
                        
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    print(i,"  Accuracy score = ",accuracy_score( y_test,y_pred) )
    print( classification_report(y_test,y_pred) )
    print( confusion_matrix(y_test,y_pred) )

In [ ]:
from sklearn.ensemble import AdaBoostClassifier

clf = make_pipeline(StandardScaler(), AdaBoostClassifier(n_estimators=100, random_state=0) )
clf.fit( X_train, y_train )
y_pred = clf.predict( X_test )
print("Accuracy score = ",accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

In [ ]:
import xgboost as xgb
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import mean_squared_error
import pandas as pd
import numpy as np

print(  xgb.XGBClassifier() )

parameters = {'learning_rate': [0.01, 0.05], #so called `eta` value
              'max_depth': [20],
              'min_child_weight': [11],
              'silent': [1],
              'subsample': [0.8],
              'colsample_bytree': [0.7],
              'n_estimators': [500], #number of trees, change it to 1000 for better results
              'seed': [1337]}

xgb_model = xgb.XGBClassifier()

clf = GridSearchCV(xgb_model, parameters, n_jobs=5, 
                   cv=StratifiedKFold( n_splits = 2, shuffle=True), 
                   scoring='roc_auc',
                   verbose=2, 
                   refit=True)

clf.fit( X_train, y_train )
y_pred = clf.predict( X_test )
print( y_pred )
print("Accuracy score = ",accuracy_score(y_test,y_pred))
print( classification_report(y_test,y_pred) )
print(confusion_matrix(y_test,y_pred))

clf.best_params_

In [9]:
import xgboost as xgb
from sklearn.metrics import mean_squared_error
import pandas as pd
import numpy as np

clf = xgb.XGBClassifier(colsample_bytree = 0.7,
                        learning_rate = 0.1,
                        max_depth = 20,
                        min_child_weight = 11,
                        n_estimators = 100,
                        seed = 1337,
                        silent = 1,
                        subsample = 0.8)
clf.fit( X_train, y_train )
y_pred = clf.predict( X_test )
print( y_pred )
print("Accuracy score = ",accuracy_score(y_test,y_pred))
print( classification_report(y_test,y_pred) )
print(confusion_matrix(y_test,y_pred))

[3 3 3 ... 0 0 3]
Accuracy score =  0.7648423456250304
              precision    recall  f1-score   support

           0       0.96      0.75      0.85     37000
           1       0.04      0.10      0.06       583
           2       0.03      0.07      0.05       677
           3       0.30      0.60      0.40      6062
           4       0.35      0.72      0.47       378
           5       0.92      0.80      0.86      3496
           6       0.61      0.84      0.71     11132
           7       0.51      0.14      0.22      4089
           8       0.79      0.43      0.56        44
           9       1.00      0.97      0.98     18871

    accuracy                           0.76     82332
   macro avg       0.55      0.54      0.52     82332
weighted avg       0.83      0.76      0.78     82332

[[27863     0   635  7601   110    22   721    41     0     7]
 [    2    60    46    94     2     0   336    43     0     0]
 [   30    58    46    82     0     0   420    41     0     

In [ ]:
li = ['linear', 'poly', 'rbf', 'sigmoid', 'precomputed']
ker = li[0]

In [ ]:
#Multi-class clasification using ovo

import numpy as np
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
print("Kernel = ",ker,"   Decision Boundary = OvO")
clf = make_pipeline(StandardScaler(), SVC(gamma='auto',decision_function_shape='ovo',kernel=ker))
#clf = SVC(gamma='auto',decision_function_shape='ovo',kernel=ker)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print("Accuracy score = ",accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

In [ ]:
#Multi-class clasification using ovr

import numpy as np
from sklearn.pipeline import make_pipeline
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import SVC
print("Kernel = ",ker,"   Decision Boundary = OvR")
clf = make_pipeline(StandardScaler(), OneVsRestClassifier(SVC(gamma='auto', kernel=ker)))
#clf = OneVsRestClassifier(SVC(gamma='auto', kernel=ker))
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print("Accuracy score = ",accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

Kernel =  linear    Decision Boundary = OvR


In [ ]:
#Attack or not 
X_train = data_Train[selected]
y_train = data_Train['label']
X_test = data_Test[selected]
y_test = data_Test['label']

In [ ]:
from sklearn.svm import LinearSVC
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_classification

clf = make_pipeline(StandardScaler(), LinearSVC(random_state=0, tol=1e-4, max_iter=1000))
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print("Accuracy score = ",accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

Accuracy score =  0.7841058154787932
              precision    recall  f1-score   support

           0       0.95      0.55      0.69     37000
           1       0.73      0.98      0.83     45332

    accuracy                           0.78     82332
   macro avg       0.84      0.76      0.76     82332
weighted avg       0.83      0.78      0.77     82332



In [ ]:
from imblearn.ensemble import BalancedBaggingClassifier

clf = BalancedBaggingClassifier(sampling_strategy='majority',n_estimators=20,base_estimator=make_pipeline(StandardScaler(), LinearSVC(random_state=0, tol=1e-4, max_iter=1000)))
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print("Accuracy score = ",accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

Accuracy score =  0.7849317397852597
              precision    recall  f1-score   support

           0       0.83      0.65      0.73     37000
           1       0.76      0.89      0.82     45332

    accuracy                           0.78     82332
   macro avg       0.80      0.77      0.78     82332
weighted avg       0.79      0.78      0.78     82332



In [ ]:
import numpy as np
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC


print("Kernel = ",ker)
clf = make_pipeline(StandardScaler(), SVC(gamma='auto',kernel=ker,probability=True))
#clf = SVC(gamma='auto',decision_function_shape='ovo',kernel=ker)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print("Accuracy score = ",accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

Kernel =  linear


In [ ]:
def roc_curve_details(prediction,y_test):
    print("ROC Score : ",roc_auc_score(y_test, prediction))
    fpr, tpr, _ = roc_curve(y_test, prediction)
    plt.clf()
    plt.plot(fpr, tpr)
    plt.xlabel('FPR')
    plt.ylabel('TPR')
    plt.title('ROC curve')
    plt.show()

In [ ]:
y_pred = clf.predict_proba(X_test)
roc_curve_details(y_pred[:,1],y_test)

In [ ]:
import numpy as np
from sklearn.linear_model import SGDClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline


clf = make_pipeline(StandardScaler(),SGDClassifier(max_iter=100000, tol=1e-7))
#clf = SGDClassifier(max_iter=100000, tol=1e-7)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print("Accuracy score = ",accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))